# Generated by Django 5.1 on 2024-08-26 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_Name', models.CharField(max_length=200)),
                ('last_Name', models.CharField(max_length=200)),
                ('emial', models.EmailField(max_length=254)),
                ('phone_nmb', models.CharField(max_length=11)),
                ('instrument_type', models.TextField()),
            ],
        ),
    ]
