# Generated by Django 5.1 on 2024-08-26 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musician_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='musician',
            old_name='emial',
            new_name='email',
        ),
    ]
