# Generated by Django 5.1 on 2024-08-26 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musician_app', '0002_rename_emial_musician_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
